### PR TITLE
Add warning to store:dispatch docs

### PR DESCRIPTION
**Pull request by Jaguar-515**

### CODE REVIEW

**Comment by ZoteTheMighty** [comment]
Could you explain in the description what situations this addresses? The way this is worded now doesn't seem accurate to me.

**Comment by Jaguar-515** [comment]
Apologizes for the late reply. I was busy with a lot of things at the time.

This addresses a situation where you intend to add an array/dictionary of values to an existing state without using any middleware.

**Comment by ZoteTheMighty** [comment]
Do you mean to say that arrays of values will overwrite each other instead of merging? Doesn't that depend on how your actions and reducers are written?

**Comment by Jaguar-515** [comment]
I did mean to say that.

**Comment by ZoteTheMighty** [comment]
I suspect this may be just a misunderstanding! When you dispatch an action, Rodux processes it via the reducers that you wrote. If you have a reducer that handles an action with a list of items, the reducer can be implemented in whatever way is useful.

The first example [here in the docs](https://roblox.github.io/rodux/introduction/reducers/) demonstrates this; `friendsReducer`  outputs a new list that appends the new items from the action to the existing state.

**Pull request closed without merging**
