### PR TITLE
Dark mode for documentation

### PR DESCRIPTION
**Pull request by Nickuhhh**
Redux's documentation is a health hazard. I believe I'm suffering from eye fatigue looking at the bright white colors.

This will acknowledge any health concerns as well as provide a seamless reading experience.

Checklist before submitting:
* [X] Added entry to `CHANGELOG.md`
* [X] Added/updated relevant tests
* [X] Added/updated documentation

### CODE REVIEW

**Review by ZoteTheMighty — APPROVED** [review]
Thank you for the submission! This looks good to me, once you sign the CLA I can merge it and update the docs.

**Comment by Nickuhhh** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ZoteTheMighty** [comment]
Commenting to retrigger the CLA bot

**Comment by Nickuhhh** [comment]
It's been 2 hours since you merged it and it doesn't seem to actually be changing anything?

**Pull request merged**
